let artistas=[
    {foto:"https://firebasestorage.googleapis.com/v0/b/historia-artistas.appspot.com/o/SHAKIRA.jpg?alt=media&token=3b41f2d8-4f79-4230-ad56-e3fb4b14e867",Historia:"Shakira Isabel Mebarak Ripoll, nacida en Barranquilla, Colombia el 2 de febrero de 1977, es una cantante, compositora y bailarina colombiana que emergió en la escena de la música latina a principios de los 90 y desde el primer momento se convirtió en el número 1latino en ventas."},
    {foto:"https://firebasestorage.googleapis.com/v0/b/historia-artistas.appspot.com/o/HARRY%20STYLES.jpg?alt=media&token=e56e3d2a-6c6d-4f29-bcbb-854d6a86db53",Historia:"Harry Styles nació en Cheshire (Reino Unido) en 1994 y creció junto a su madre y su hermana después de que sus padres se divorciaran. Pronto comenzó a interesarse por la música, llegando a montar su propia banda. En 2010 fue seleccionado para participar en la edición británica del programa Factor X ."},
    {foto:"https://firebasestorage.googleapis.com/v0/b/historia-artistas.appspot.com/o/DUA%20LIPA.jpeg?alt=media&token=94194e2d-1e05-49c6-8451-88511808b1cd",Historia:"Dua Lipa (Londres, 22 de agosto de 1995) es una cantante, compositora, modelo y actriz británica de origen albanokosovar. Después de trabajar como modelo, firmó con Warner Bros. Records en 2014 y lanzó su álbum debut homónimo en 2017."},
    {foto:"https://firebasestorage.googleapis.com/v0/b/historia-artistas.appspot.com/o/ROSALIA.webp?alt=media&token=51af3a1a-1e2a-4cbf-8446-0d0210908679",Historia:"Rosalía nació el 25 de septiembre de 1992​ en el Hospital General de Catalunya en San Cugat del Vallés y se crio en San Esteban de Sasroviras.​ Es la segunda hija del matrimonio formado por José Manuel Vila y Pilar Tobella. Su hermana mayor, Pilar, actualmente trabaja con ella como su estilista."},
    {"Es una cantante inglesa, nacida el 5 de mayo de 1988 en la ciudad británica de Tottenham, al norte de Londres. Es hija de la inglesa Penny Adkins y del galés Mark Evans, un hombre alcohólico que las abandonó cuando Adele tenía sólo dos años, dejándole así a su madre la responsabilidad de criarla."},
    {"Sia Kate Isobelle Furler (Adelaida, Australia, 18 de diciembre del 1975) conocida simplemente como Sia, es una cantautora, productora, actriz, directora y escritora australiana. Desde 2018 forma parte del supergrupo LSD junto a Labrinth y Diplo. En 2000, su sencillo «Taken for Granted» fue un éxito en el Reino Unido."},
    {"David Guetta es hijo de Pierre Guetta, un sociólogo francés, aunque después reconvertido en restaurador, de ascendencia franco-italiana, originario de Tetuán, Marruecos y con raíces judías sefarditas;​ y de Monique, una francesa de origen belga."},
    {"David Garrett, quien nació en 1980 en Aquisgrán, tuvo su primer violín a los cuatro años, realizó su primera actuación con la Filarmónica de Hamburgo a los 10, y se convirtió en el artista más joven en ser contratado por el prestigioso sello discográfico Deutsche Grammophon Gesellschaft, a los 13."},
    {"Hija de un vendedor y una farmacéutica, Amy Jade Winehouse nació el 14 septiembre de 1983 en Southgate, Londres, en el seno de una familia humilde. Su padre le inculcó el amor por el jazz y ella siempre tuvo claro que quería convertirse en una buena intérprete de ese género musical."},
    {"Banda del llamado Heavy comercial, formada en New Jersey con Jon Bon Jovi (nacido como John Bongiovi, en marzo de 1962) al frente. Es uno de los grupos de rock que más han vendido desde su creación en 1983; lo integran con Richie Sambora (1959), David Bryan (1962), Alec John Such (1956) y Tico Torres (1953)."},

]